# Generated by Django 2.2.3 on 2019-08-06 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='user',
            field=models.ManyToManyField(related_name='users', through='quiz.QuizResults', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizresults',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_to_user', to='quiz.Quiz'),
        ),
        migrations.AlterField(
            model_name='quizresults',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_quiz', to=settings.AUTH_USER_MODEL),
        ),
    ]
